# Generated by Django 4.0.3 on 2022-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type_of', models.CharField(default='', max_length=100)),
                ('loc', models.CharField(default='', max_length=200)),
                ('website', models.URLField(max_length=500)),
                ('open_time', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('reviews', models.CharField(default='', max_length=100)),
                ('star_rating', models.CharField(default='', max_length=100)),
                ('review_category', models.CharField(default='', max_length=100)),
                ('tour', models.BooleanField()),
                ('img_url', models.URLField(default='', max_length=1000)),
                ('gmaps', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('number_of_reviews', models.CharField(default='', max_length=100)),
                ('type_of', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(default='', max_length=100)),
                ('guided_tours', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
