# Generated by Django 4.0 on 2022-02-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=5, max_digits=10)),
                ('type_c', models.CharField(max_length=100)),
            ],
        ),
    ]
