# Generated by Django 3.2.16 on 2023-01-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('GuestCI', 'Guest'),
        #migrations.RenameField('Booking', 'GuestCI', 'Guest')
    ]
