# Generated by Django 3.2.16 on 2023-01-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20230123_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='expired',
            new_name='isexpired',
        ),
    ]
