# Generated by Django 3.2.16 on 2023-02-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_rename_expired_booking_isexpired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest.guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nights',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest.room'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
