# Generated by Django 3.2.16 on 2023-03-13 04:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20230206_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration', models.DateField()),
                ('is_valid', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest.guest')),
            ],
        ),
    ]
