# Generated by Django 4.0 on 2022-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='guided_tours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
    ]
