# Generated by Django 4.0.2 on 2022-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_inputfield_guided_tours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='img_url',
            field=models.URLField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
